// src/lib/components/decorative/OrganicShape.svelte
<script>
  export let type = "blob1"; // blob1, blob2, blob3
  export let fill = "#2d6a4f";
  export let width = "100%";
  export let height = "100%";
  export let opacity = 1.0;
  export let rotate = 0;
</script>

<div 
  class="organic-shape" 
  style="width: {width}; height: {height}; transform: rotate({rotate}deg); opacity: {opacity};"
>
  {#if type === "blob1"}
    <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" class="w-full h-full">
      <path 
        d="M44.7,-76.4C58.8,-69.2,71.8,-59.1,81.6,-45.8C91.4,-32.6,98,-16.3,97.1,0.2C96.2,16.7,87.8,33.4,76.9,47.3C66,61.2,52.6,72.3,37.6,79.2C22.6,86.1,6,88.8,-9.7,86.4C-25.4,84,-40.2,76.5,-52.8,65.8C-65.4,55.1,-75.8,41.2,-81.7,25.4C-87.6,9.6,-89,-7.9,-85.2,-23.9C-81.4,-39.9,-72.4,-54.4,-60.1,-62.8C-47.8,-71.2,-32.2,-72.5,-17.3,-75.9C-2.4,-79.3,11.8,-84.8,25.9,-85.2C40,-85.6,53.9,-80.9,44.7,-76.4Z" 
        transform="translate(100 100)" 
        {fill}
      />
    </svg>
  {:else if type === "blob2"}
    <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" class="w-full h-full">
      <path 
        d="M37.1,-63.2C49.2,-56.8,60.7,-47.4,69.1,-35.2C77.5,-23,82.8,-8,82.6,7.2C82.4,22.4,76.7,37.8,67.8,50.1C58.9,62.4,46.8,71.6,33.4,76.9C20,82.2,5.3,83.6,-8.7,81.1C-22.7,78.6,-36,72.2,-47.8,63.2C-59.6,54.2,-70,42.6,-75.2,29.1C-80.4,15.6,-80.4,0.2,-77.8,-14.2C-75.2,-28.6,-70,-42,-60.9,-52.8C-51.8,-63.6,-38.8,-71.8,-25.7,-73.2C-12.6,-74.6,0.6,-69.2,14.3,-65.8C28,-62.4,42.2,-61,37.1,-63.2Z" 
        transform="translate(100 100)" 
        {fill}
      />
    </svg>
  {:else if type === "blob3"}
    <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" class="w-full h-full">
      <path 
        d="M51.2,-85.1C66.6,-78.2,79.5,-66.8,86.8,-52.4C94.1,-38,95.8,-20.6,92.6,-4.8C89.4,11,81.3,25.2,71.8,37.8C62.3,50.4,51.4,61.4,38.7,68.9C26,76.4,11.5,80.4,-2.8,85.2C-17.1,90,-33.2,95.6,-46.8,92.4C-60.4,89.2,-71.5,77.2,-78.9,63.1C-86.3,49,-90,32.8,-88.1,17.2C-86.2,1.6,-78.7,-13.4,-70.4,-27.2C-62.1,-41,-53,-53.6,-41.2,-62.2C-29.4,-70.8,-14.7,-75.4,1.2,-77.8C17.1,-80.2,34.2,-80.4,51.2,-85.1Z" 
        transform="translate(100 100)" 
        {fill}
      />
    </svg>
  {/if}
</div>

<style>
  .organic-shape {
    display: block;
    position: relative;
  }
  
  .organic-shape svg {
    display: block;
  }
</style>

// src/components/decorative/OrganicShape.tsx
import React from 'react';

interface OrganicShapeProps {
  type?: 'blob1' | 'blob2' | 'blob3';
  fill?: string;
  width?: string;
  height?: string;
  opacity?: number;
  rotate?: number;
}

export default function OrganicShape({
  type = 'blob1',
  fill = '#2d6a4f',
  width = '100%',
  height = '100%',
  opacity = 1.0,
  rotate = 0
}: OrganicShapeProps) {
  const paths = {
    blob1: "M44.7,-76.4C58.8,-69.2,71.8,-59.1,81.6,-45.8C91.4,-32.6,98,-16.3,97.1,0.2C96.2,16.7,87.8,33.4,76.9,47.3C66,61.2,52.6,72.3,37.6,79.2C22.6,86.1,6,88.8,-9.7,86.4C-25.4,84,-40.2,76.5,-52.8,65.8C-65.4,55.1,-75.8,41.2,-81.7,25.4C-87.6,9.6,-89,-7.9,-85.2,-23.9C-81.4,-39.9,-72.4,-54.4,-60.1,-62.8C-47.8,-71.2,-32.2,-72.5,-17.3,-75.9C-2.4,-79.3,11.8,-84.8,25.9,-85.2C40,-85.6,53.9,-80.9,44.7,-76.4Z",
    blob2: "M37.1,-63.2C49.2,-56.8,60.7,-47.4,69.1,-35.2C77.5,-23,82.8,-8,82.6,7.2C82.4,22.4,76.7,37.8,67.8,50.1C58.9,62.4,46.8,71.6,33.4,76.9C20,82.2,5.3,83.6,-8.7,81.1C-22.7,78.6,-36,72.2,-47.8,63.2C-59.6,54.2,-70,42.6,-75.2,29.1C-80.4,15.6,-80.4,0.2,-77.8,-14.2C-75.2,-28.6,-70,-42,-60.9,-52.8C-51.8,-63.6,-38.8,-71.8,-25.7,-73.2C-12.6,-74.6,0.6,-69.2,14.3,-65.8C28,-62.4,42.2,-61,37.1,-63.2Z",
    blob3: "M51.2,-85.1C66.6,-78.2,79.5,-66.8,86.8,-52.4C94.1,-38,95.8,-20.6,92.6,-4.8C89.4,11,81.3,25.2,71.8,37.8C62.3,50.4,51.4,61.4,38.7,68.9C26,76.4,11.5,80.4,-2.8,85.2C-17.1,90,-33.2,95.6,-46.8,92.4C-60.4,89.2,-71.5,77.2,-78.9,63.1C-86.3,49,-90,32.8,-88.1,17.2C-86.2,1.6,-78.7,-13.4,-70.4,-27.2C-62.1,-41,-53,-53.6,-41.2,-62.2C-29.4,-70.8,-14.7,-75.4,1.2,-77.8C17.1,-80.2,34.2,-80.4,51.2,-85.1Z"
  };

  return (
    <div 
      className="organic-shape block relative"
      style={{ 
        width, 
        height, 
        transform: `rotate(${rotate}deg)`, 
        opacity 
      }}
    >
      <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" className="w-full h-full block">
        <path 
          d={paths[type]} 
          transform="translate(100 100)" 
          fill={fill}
        />
      </svg>
    </div>
  );
}
